/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CaculatorController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class CaculatorView extends javax.swing.JFrame {

    public CaculatorView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JButton getBtDot() {
        return btDot;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMC = new javax.swing.JButton();
        btMR = new javax.swing.JButton();
        btMadd = new javax.swing.JButton();
        btMsub = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btDivide = new javax.swing.JButton();
        btPercent = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btMultiple = new javax.swing.JButton();
        btInvert = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btSub = new javax.swing.JButton();
        btSqrt = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btDot = new javax.swing.JButton();
        btNegate = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btResult = new javax.swing.JButton();
        text = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btAllClear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 10, 10));

        btMC.setBackground(new java.awt.Color(255, 236, 172));
        btMC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMC.setText("MC");
        jPanel1.add(btMC);

        btMR.setBackground(new java.awt.Color(255, 236, 172));
        btMR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMR.setText("MR");
        jPanel1.add(btMR);

        btMadd.setBackground(new java.awt.Color(255, 236, 172));
        btMadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMadd.setText("M+");
        jPanel1.add(btMadd);

        btMsub.setBackground(new java.awt.Color(255, 236, 172));
        btMsub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMsub.setText("M-");
        jPanel1.add(btMsub);

        btDel.setBackground(new java.awt.Color(153, 255, 153));
        btDel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btDel.setText("<--");
        jPanel1.add(btDel);

        bt7.setBackground(new java.awt.Color(204, 204, 255));
        bt7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt7.setText("7");
        jPanel1.add(bt7);

        bt8.setBackground(new java.awt.Color(204, 204, 255));
        bt8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8);

        bt9.setBackground(new java.awt.Color(204, 204, 255));
        bt9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt9.setText("9");
        jPanel1.add(bt9);

        btDivide.setBackground(new java.awt.Color(153, 255, 153));
        btDivide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btDivide.setText("÷");
        btDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivideActionPerformed(evt);
            }
        });
        jPanel1.add(btDivide);

        btPercent.setBackground(new java.awt.Color(153, 255, 153));
        btPercent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btPercent.setText("%");
        jPanel1.add(btPercent);

        bt4.setBackground(new java.awt.Color(204, 204, 255));
        bt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt4.setText("4");
        jPanel1.add(bt4);

        bt5.setBackground(new java.awt.Color(204, 204, 255));
        bt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt5.setText("5");
        jPanel1.add(bt5);

        bt6.setBackground(new java.awt.Color(204, 204, 255));
        bt6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt6.setText("6");
        jPanel1.add(bt6);

        btMultiple.setBackground(new java.awt.Color(153, 255, 153));
        btMultiple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMultiple.setText("X");
        jPanel1.add(btMultiple);

        btInvert.setBackground(new java.awt.Color(153, 255, 153));
        btInvert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btInvert.setText("1/X");
        jPanel1.add(btInvert);

        bt1.setBackground(new java.awt.Color(204, 204, 255));
        bt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt1.setText("1");
        jPanel1.add(bt1);

        bt2.setBackground(new java.awt.Color(204, 204, 255));
        bt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2);

        bt3.setBackground(new java.awt.Color(204, 204, 255));
        bt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt3.setText("3");
        jPanel1.add(bt3);

        btSub.setBackground(new java.awt.Color(153, 255, 153));
        btSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSub.setText("-");
        jPanel1.add(btSub);

        btSqrt.setBackground(new java.awt.Color(153, 255, 153));
        btSqrt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSqrt.setText("√");
        jPanel1.add(btSqrt);

        bt0.setBackground(new java.awt.Color(204, 204, 255));
        bt0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel1.add(bt0);

        btDot.setBackground(new java.awt.Color(204, 204, 255));
        btDot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btDot.setText(".");
        jPanel1.add(btDot);

        btNegate.setBackground(new java.awt.Color(153, 255, 153));
        btNegate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btNegate.setText("+/-");
        jPanel1.add(btNegate);

        btAdd.setBackground(new java.awt.Color(153, 255, 153));
        btAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAdd.setText("+");
        jPanel1.add(btAdd);

        btResult.setBackground(new java.awt.Color(153, 255, 153));
        btResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btResult.setText("=");
        btResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResultActionPerformed(evt);
            }
        });
        jPanel1.add(btResult);

        text.setEditable(false);
        text.setBackground(new java.awt.Color(229, 252, 255));
        text.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text.setText("0");

        btAllClear.setText("All Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllClear))
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtDel() {
        return btDel;
    }

    public JTextField getText() {
        return text;
    }

    public JButton getBt0() {
        return bt0;
    }

    public JButton getBt1() {
        return bt1;
    }

    public JButton getBt2() {
        return bt2;
    }

    public JButton getBt3() {
        return bt3;
    }

    public JButton getBt4() {
        return bt4;
    }

    public JButton getBt5() {
        return bt5;
    }

    public JButton getBt6() {
        return bt6;
    }

    public JButton getBt7() {
        return bt7;
    }

    public JButton getBt8() {
        return bt8;
    }

    public JButton getBt9() {
        return bt9;
    }
    public JLabel getBtAllClear() {
        return btAllClear;
    }

    public JButton getBtNegate() {
        return btNegate;
    }

    public JButton getBtAdd() {
        return btAdd;
    }

    public JButton getBtResult() {
        return btResult;
    }

    public JButton getBtSub() {
        return btSub;
    }

    public JButton getBtMultiple() {
        return btMultiple;
    }

    public JButton getBtDivide() {
        return btDivide;
    }

    public JButton getBtPercent() {
        return btPercent;
    }

    public JButton getBtInvert() {
        return btInvert;
    }

    public JButton getBtSqrt() {
        return btSqrt;
    }

    public JButton getBtMadd() {
        return btMadd;
    }

    public JButton getBtMR() {
        return btMR;
    }

    public JButton getBtMsub() {
        return btMsub;
    }

    public JButton getBtMC() {
        return btMC;
    }
    
    

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt8ActionPerformed

    private void btDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDivideActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void btResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btResultActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        
    }//GEN-LAST:event_bt0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaculatorView().setVisible(true);
            }
        });
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAdd;
    private javax.swing.JLabel btAllClear;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btDivide;
    private javax.swing.JButton btDot;
    private javax.swing.JButton btInvert;
    private javax.swing.JButton btMC;
    private javax.swing.JButton btMR;
    private javax.swing.JButton btMadd;
    private javax.swing.JButton btMsub;
    private javax.swing.JButton btMultiple;
    private javax.swing.JButton btNegate;
    private javax.swing.JButton btPercent;
    private javax.swing.JButton btResult;
    private javax.swing.JButton btSqrt;
    private javax.swing.JButton btSub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables

}
